- repository: https://github.com/nabedev/next-firebase-auth-handson
  description: |
    Apollo製のTODOアプリ

  demo: https://user-images.githubusercontent.com/26590545/177315753-ec55e865-3423-425f-8e4e-d963f2b176b9.png

- repository: https://github.com/nabedev/blog
  description: |
    
  demo: https://user-images.githubusercontent.com/26590545/177299422-ab4e4ba0-b95c-4a5a-9053-0c8a466a4ced.png

- repository: https://github.com/nabedev/HoldemAdviser
  description: |
    ライブラリを使用することによるブラックボックスが嫌でプレーンなJS,HTML,CSSで作成したテキサスホールデム学習ゲーム。

  demo: https://github.com/nabedev/HoldemAdviser/blob/master/holdem-adviser-demo.gif?raw=true

- repository: https://github.com/nabedev/flickr-bundle-downloader
  description: |
    Flickr.comのChrome拡張機能
  demo: https://user-images.githubusercontent.com/26590545/140095941-e66a16ea-9fe9-480e-8c12-f3d54e580f73.mov
  type: "video"

- repository: https://github.com/nabedev/enhance-chrome-history-search
  description: |
    Chromeの履歴検索を強化する拡張機能。
  demo: https://github.com/nabedev/enhance-chrome-history-search/blob/master/enhance-chrome-history-demo.gif?raw=true

- repository: https://github.com/nabedev/times-automation
  description: |
    タイムズカーシェアの予約自動化用、ヘッドレスChrome。

- repository: https://github.com/nabedev/simple-webtracker
  description: |
    パンデミックの時に作った超シンプルクローラー。
    定期的にマスクの在庫確認しにいってSlackで通知するようにしたが、在庫復活する時だいたい寝てて買えなくてやめた。
