- name: Flickr Bundle Downloader
  description: Flickr.comで写真の複数ダウンロードを可能にするChrome拡張機能。
  repository: https://github.com/wtnb93/flickr-bundle-downloader
  demo: ""

- name: Hisotry Search
  description: Chromeの履歴検索を強化する拡張機能。
  repository: https://github.com/wtnb93/enhance-chrome-history-search
  demo: https://github.com/wtnb93/enhance-chrome-history-search/blob/master/enhance-chrome-history-demo.gif?raw=true

- name: Holdem Adviser
  description: テキサスホールデムの基礎を学ぶゲーム。
  repository: https://github.com/wtnb93/HoldemAdviser
  demo: https://github.com/wtnb93/HoldemAdviser/blob/master/holdem-adviser-demo.gif?raw=true

