- repository: https://github.com/nabedev/blog
  description: |
    このサイト
    Gatsby.js

- repository: https://github.com/nabedev/flickr-bundle-downloader
  description: |
    Flickr.comで写真の複数ダウンロードを可能にするChrome拡張機能。
    Fech API の AbortController で正しく(?)リクエストを中断するようにしている。
  demo: https://user-images.githubusercontent.com/26590545/140095941-e66a16ea-9fe9-480e-8c12-f3d54e580f73.mov
  type: "video"

- repository: https://github.com/nabedev/enhance-chrome-history-search
  description: |
    Chromeの履歴検索を強化する拡張機能。
    ReactのHooks APIを試してみたくて作った。
    UIはReact、ShadowDOMでDOMのマークアップ、スタイル、動作の影響を受けないよう(もしくは壊さないよう)にした。
  demo: https://github.com/nabedev/enhance-chrome-history-search/blob/master/enhance-chrome-history-demo.gif?raw=true

- repository: https://github.com/nabedev/times-automation
  description: |
    タイムズカーシェアの予約をヘッドレスブラウザで自動化。
    複数のステーションの空き情報をいちいち見に行くのが怠かったから作った。

- repository: https://github.com/nabedev/simple-webtracker
  description: |
    パンデミックの時に作った超シンプルクローラー。
    定期的にマスクの在庫確認しにいってSlackで通知するようにしたが、在庫復活する時だいたい寝てて買えなくてやめた。

- repository: https://github.com/nabedev/HoldemAdviser
  description: |
    テキサスホールデム(ポーカー)の基礎を学ぶゲーム。
    ずっと昔に趣味で作ったのをずっと昔にリファタした。
    アニメーションはCSS、ロジックはPure JavaScriptで書いた。
    GitHub Pages でホスティングしている。
    謎にWeb Audio APIを使っていて音が出る。
  demo: https://github.com/nabedev/HoldemAdviser/blob/master/holdem-adviser-demo.gif?raw=true
